# Generated by Django 6.0.3 on 2026-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('GINECO', 'Gynécologue'), ('TRAITANT', 'Médecin traitant'), ('DENTISTE', 'Dentiste'), ('PEDIATRE', 'Pédiatre'), ('CARDIOLOGUE', 'Cardiologue')], default='TRAITANT', max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='statue',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupé')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=5),
        ),
    ]
