# Generated by Django 6.0.3 on 2026-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_medecin_specialite_alter_medecin_statue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='statue',
            field=models.CharField(default='en attente', max_length=11),
        ),
    ]
