# Generated by Django 6.0.3 on 2026-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rendezvous_statue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='statue',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(default='attente', max_length=11),
        ),
    ]
