# Generated by Django 6.0.3 on 2026-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_rendezvous_statue_rendezvous_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(blank=True, default=''),
        ),
    ]
